### PR TITLE
Combine two python scripts into one and add an applescript to simulate clicking.

### PR DESCRIPTION
**Pull request by ysrotciv**
And only simulate click action when location changed instead of  every 1 second.

### CODE REVIEW

**Comment by pawin** [comment]
awesome, but would it be better if we use AppleScript for clicking instead? [#29](https://github.com/kahopoon/Pokemon-Go-Controller/issues/29)

**Comment by JoniSykes** [comment]
Is the auto clicking required or just to make navigation easier?

**Comment by ysrotciv** [comment]
@pawin I'm not familiar with AppleScript, but I would like to try.

**Comment by ysrotciv** [comment]
@JoniSykes Just to make it easier, not necessary.

**Comment by deden** [comment]
Awesome!
It's nice idea for combine two scripts into one file.

But sometimes, using two scripts is useful for tweak the initial settings, i.e setup initial position before the mouse can not be used when autoClicker running.

Usually I exec the readAndChangeXML.py first to check the connection to controller and also for double check location, and when everything is okay just run the autoClicker script.

**Comment by deden** [comment]
After give it a try, I found this single script is more stable and doesn't interrupted mouse interaction as long as the location didn't change.

**Comment by posixpascal** [comment]
This is the correct applescript to make a click:

```
tell application "System Events" to tell process "Xcode"
    click menu item "<gpx filename>" of menu 1 of menu item "Simulate Location" of menu 1 of menu bar item "Debug" of menu bar 1
end tell
```

This does NOT interupt mouse interaction and can be invoked from python using:

`os.system("osascript click.applescript");`

I'm running this atm with zero problems.
The next thing would be to write a MacOS app instead of an extra iPad app. 
This way we don't need the absurd setup of 3 apple devices.   

Also made a pull requests including the applescript:

**Comment by ysrotciv** [comment]
Thanks @posixpascal for supplying applescript.
Now the xcode don't need to be on front any more.

**Comment by posixpascal** [comment]
Yes. Also we don’t need the mouse highjacking anymore.
Next step would be to add a MacOS app which displays the map.

Who wants to open a branch for that? ;)

> Am 15.07.2016 um 13:16 schrieb 杨帅 notifications@github.com:
> 
> Thanks @posixpascal https://github.com/posixpascal for supplying applescript.
> Now the xcode don't need to be on front any more.

How about we are using Electron instead of native swift to build a google maps application?
That way we open doors for Windows & Linux systems as well.

**Comment by Abeldvlpr** [comment]
The Mac app is a good idea but I think it's useless to implement it in Electron since we still need Xcode to simulate the location and it is only available for macOS..

**Comment by posixpascal** [comment]
I think you can change the location using adb as well. At least in the simulator. I'll look into this if I have enough spare time.

**Comment by Abeldvlpr** [comment]
My bad, forgot about Android..

**Pull request closed without merging**
